# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tlog < Formula
  desc "Simple CLI that helps log time on JIRA issues."
  homepage "https://github.com/What-If-I/tlog"
  version "0.0.5"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.5/tlog_0.0.5_Darwin_arm64.tar.gz"
      sha256 "0c39d8eba8fc8456049b28b7ca4e7c7f369c9f9c087e9def2debe81b73daf24f"

      def install
        bin.install "tlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.5/tlog_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "24bfeb55eeefe3e8ea477a90dafb25a41885057ddb597374f9aa322dfd0871e4"

      def install
        bin.install "tlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.5/tlog_0.0.5_Linux_arm64.tar.gz"
      sha256 "483ad9398159750700e7d6171d8c34fc63b6a90fa5dd8ab27b639c5068bf4a9e"

      def install
        bin.install "tlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.5/tlog_0.0.5_Linux_x86_64.tar.gz"
      sha256 "c47b49c54f78347ba9a1363f2dc010070d70d8969051c3102ea4a93f99142073"

      def install
        bin.install "tlog"
      end
    end
  end

  test do
    system "test -f #{bin}/tlog"
  end
end
