# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tlog < Formula
  desc "Simple CLI that helps log time on JIRA issues."
  homepage "https://github.com/What-If-I/tlog"
  version "0.0.4"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.4/tlog_0.0.4_Darwin_arm64.tar.gz"
      sha256 "ac01b09660a92faee6e596440e89890606539317f4f3b917caa96a78ad0f99a2"

      def install
        bin.install "tlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.4/tlog_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "9ed28b8ec730ca0796aad481066bbc8b3a34218c721cafc824a265d2a9a3626f"

      def install
        bin.install "tlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.4/tlog_0.0.4_Linux_arm64.tar.gz"
      sha256 "bc3c55c265ddb83d0bfd14b890b5d8b05b94b745bbf65c07ff9fb7e122a0651c"

      def install
        bin.install "tlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/What-If-I/tlog/releases/download/v0.0.4/tlog_0.0.4_Linux_x86_64.tar.gz"
      sha256 "23082d2058089fa61949e8e290339979d8b32e94deac33f1d359e97e6d56e8bd"

      def install
        bin.install "tlog"
      end
    end
  end

  test do
    system "test -f #{bin}/tlog"
  end
end
