# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tlog < Formula
  desc "Simple CLI that helps log time on JIRA issues."
  homepage "https://github.com/fetinin/tlog"
  version "0.0.6"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fetinin/tlog/releases/download/v0.0.6/tlog_0.0.6_Darwin_arm64.tar.gz"
      sha256 "dffbba678d40b95ae1a13a46c05c4c792aca9533b69b62e4d281c0c30afe5bbe"

      def install
        bin.install "tlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fetinin/tlog/releases/download/v0.0.6/tlog_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "7cd8654ff9af278077cbe3b1ee8a1f055e4a817af20e2884007474bf71c9a299"

      def install
        bin.install "tlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fetinin/tlog/releases/download/v0.0.6/tlog_0.0.6_Linux_arm64.tar.gz"
      sha256 "7d8409584385ee337524ec0c47c1c8d5b43a4de2b96af1bc5013b509ba8a0c52"

      def install
        bin.install "tlog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fetinin/tlog/releases/download/v0.0.6/tlog_0.0.6_Linux_x86_64.tar.gz"
      sha256 "fa83782cb845fb546d7ed36aecac07f6f49c9407b99f5acf174cf5f844587ef9"

      def install
        bin.install "tlog"
      end
    end
  end

  test do
    system "test -f #{bin}/tlog"
  end
end
